# BEGIN_KITTY_THEME
# Noctalia
include themes/ashen.conf
window_padding_width 7
shell             fish
shell_integration enabled
confirm_os_window_close -1
# END_KITTY_THEME

background_opacity  0.8
background_blur     1

# BEGIN_KITTY_FONTS
font_family      family="JetBrainsMono Nerd Font"
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS
